### PR TITLE
remove deprecated components

### PR DESCRIPTION
**Pull request by vsinghal13**
Finish deprecating `lookup_by_name` and `destroy` attributes from collector

### CODE REVIEW

**Comment by seansain** [comment]
Remove from the terraform.io docs as well: `website/docs/r/collector.html.markdown`

**Comment by seansain** [comment]
Looks like the acceptance tests are failing. Might need to make some test changes and ensure your changes work as expected.

**Comment by vsinghal13** [comment]
@seansain the acceptance tests are fixed now.

**Comment by seansain** [comment]
Great, please update the `CHANGELOG.md` with a node that this is deprecated. I think we will also have to update the unreleased version to `2.1.0` since this is breaking change.

**Comment by vsinghal13** [comment]
> Great, please update the `CHANGELOG.md` with a note that this is deprecated. I think we will also have to update the unreleased version to `2.1.0` since this is breaking change.

Changelog updated

**Pull request merged**
