### PR TITLE
Add support for contentType

### PR DESCRIPTION
**Pull request by sumo-drosiek**
Add support for contentType to meet the functionality from https://github.com/SumoLogic/terraform-provider-sumologic/pull/123

### CODE REVIEW

**Comment by seansain** [comment]
@sumo-drosiek Will you add the test in this same PR after we enable tracing for the org?

**Comment by sumo-drosiek** [comment]
@seansain sure

**Comment by sumo-drosiek** [comment]
@seansain Tests updated

**Comment by seansain** [comment]
Tested against US2 and passes

**Pull request merged**
